apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-loadbalancer
  name: fake-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-loadbalancer
  template:
    metadata:
      labels:
        app: fake-loadbalancer
    spec:
      containers:
      - image: directxman12/fake-loadbalancer
        name: fake-loadbalancer
        env:
        - name: WATCHED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fake-loadbalancer
  labels:
    app: fake-loadbalancer
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app: fake-loadbalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fake-loadbalancer
  labels:
    service-monitor: fake-loadbalancer
spec:
  selector:
    matchLabels:
      app: fake-loadbalancer
  endpoints:
  - port: web
    path: '/_metrics'
