apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-server
  name: sample-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-server
  template:
    metadata:
      labels:
        app: sample-server
    spec:
      containers:
      - image: gcr.io/maciekpytel-dev-playground/server:0.0.1
        command:
        - /bin/sh
        - -c
        - ./server
        name: sample-server
        ports:
        - name: web
          containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: sample-server
  labels:
    app: sample-server
spec:
  ports:
  - name: web
    port: 80
    targetPort: 1234
  selector:
    app: sample-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-server
  labels:
    service-monitor: sample-server
spec:
  selector:
    matchLabels:
      app: sample-server
  endpoints:
  - port: web
